version: "3.9"
services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET=${S3_BUCKET:-mlops-bucket-vicari}
      - S3_MODEL_KEY=${S3_MODEL_KEY:-epoch20.pt}
      - LOCAL_MODEL_PATH=${LOCAL_MODEL_PATH:-/app/weights/epoch20.pt}
    volumes:
      - ./backend:/app
      - ./backend/weights:/app/weights

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
