version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-jorgeguillermoolarte@gmail.com}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_acme:/data
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST:-traefik.settinel.lat}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.service=api@internal"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USER:-guillermoolarte}/fullstack-backend:${BACKEND_TAG:-latest}
    container_name: fullstack_backend
    restart: unless-stopped
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${API_DOMAIN:-api.settinel.lat}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.middlewares=cors-headers@file"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

    environment:
      - FLASK_ENV=production
      - PORT=${PORT:-5000}
      - LOCAL_MODEL_PATH=${LOCAL_MODEL_PATH:-/app/weights/epoch20.pt}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USER:-guillermoolarte}/fullstack-frontend:${FRONTEND_TAG:-latest}
    container_name: fullstack_frontend
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-settinel.lat}`) || Host(`www.${DOMAIN:-settinel.lat}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

      # HTTP to HTTPS redirect
      - "traefik.http.routers.frontend-redirect.rule=Host(`${DOMAIN:-settinel.lat}`) || Host(`www.${DOMAIN:-settinel.lat}`)"
      - "traefik.http.routers.frontend-redirect.entrypoints=web"
      - "traefik.http.routers.frontend-redirect.middlewares=redirect-to-https@file"

volumes:
  traefik_acme:
