# # traefik/dynamic.yml
# http:
#   middlewares:
#     secure-headers:
#       headers:
#         frameDeny: true
#         browserXssFilter: true
#         contentTypeNosniff: true

http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        sslRedirect: true

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  options:
    default:
      minVersion: VersionTLS12
