name: Weekly Model Retraining

on:
  schedule:
    - cron: "0 3 * * 0" # todos los domingos a las 03:00 UTC (ajusta si quieres)
  workflow_dispatch: # para ejecutarlo manualmente también

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install ultralytics boto3 torch pyyaml

      - name: Run training script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          python ./training/entrenamiento.py
